url =https://stage-emr.planetrehab.youngsoft.com/interface/login/login.php?site=bodyelitept
browser=chrome
HomePageTitle=Body Elite PT
# Default
username=eliteptadmin@yopmail.com
password=Youngsoft@12345

# Custom users
admin.username=eliteptadmin@yopmail.com
admin.password=Youngsoft@12345

doctor.username=doctor@gmail.com
doctor.password=doctor123