name: Selenium CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run Tests
      run: mvn clean test