name: Selenium CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print Debug Info
      run: |
        echo "Starting CI"
        dir

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Verify Java
      run: java -version

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Verify Chrome
      run: chrome --version

    - name: Run Tests
      run: mvn clean test -Dheadless=true